//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommercialFlight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommercialFlight()
        {
            this.FlightPersonals = new HashSet<FlightPersonal>();
            this.FilghtPlaces = new HashSet<FilghtPlace>();
            this.ScalesOnFlights = new HashSet<ScalesOnFlight>();
        }
    
        public string idFlight { get; set; }
        public decimal Distance { get; set; }
        public System.DateTime Deport { get; set; }
        public System.DateTime Arrive { get; set; }
        public float Price { get; set; }
        public Nullable<int> Disponible_Places { get; set; }
        public string Flight_To { get; set; }
        public string Flight_From { get; set; }
        public string Flight_Plane { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Destination Destination1 { get; set; }
        public virtual Plane Plane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightPersonal> FlightPersonals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilghtPlace> FilghtPlaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScalesOnFlight> ScalesOnFlights { get; set; }
    }
}
