//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPersonal
    {
        public string Personal_Rol { get; set; }
        public string Flight { get; set; }
        public string Employ { get; set; }
    
        public virtual CommercialFlight CommercialFlight { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
