//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightsDBEntities : DbContext
    {
        public FlightsDBEntities()
            : base("name=FlightsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommercialFlight> CommercialFlights { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FilghtPlace> FilghtPlaces { get; set; }
        public virtual DbSet<FlightPersonal> FlightPersonals { get; set; }
        public virtual DbSet<Plane> Planes { get; set; }
        public virtual DbSet<ScalesOnFlight> ScalesOnFlights { get; set; }
    }
}
