//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScalesOnFlight
    {
        public string idScale { get; set; }
        public System.DateTime Deport { get; set; }
        public System.DateTime Arrive { get; set; }
        public string idAirport { get; set; }
        public string idFligth { get; set; }
    
        public virtual CommercialFlight CommercialFlight { get; set; }
        public virtual Destination Destination { get; set; }
    }
}
